**main.bicep**

param environment string = 'staging'
param location string = resourceGroup().location

resource appServicePlan 'Microsoft.Web/serverfarms@2021-02-01' = {
  name: 'quickshop-asp-${environment}'
  location: location
  sku: {
    name: 'B1'
    tier: 'Basic'
  }
}

resource webApp 'Microsoft.Web/sites@2021-02-01' = {
  name: 'quickshop-web-${environment}'
  location: location
  properties: {
    serverFarmId: appServicePlan.id

az deployment group create --resource-group <rg> --template-file main.bicep --parameters environment=staging
az deployment group create --resource-group <rg> --template-file main.bicep --parameters environment=production
